'use server'
import type { Metadata } from "next"
import Header from "@/components/Header"
import Providers from "./Providers"
import Footer from "@/components/Footer"
import React from 'react'
import { getUser } from '@/lib/api/user'
import '@mantine/core/styles.css'
import '@mantine/dates/styles.css'
import '@mantine/notifications/styles.css'
import "../styles/app.scss"

import { ColorSchemeScript } from '@mantine/core'
export const generateMetadata = async (): Promise<Metadata> => {

	return {
		title: "Börds punkt Fåvitsko punkt SE",
		description: "Generated by create next app"
	}
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const userData = await getUser()
	

	return (

		<html lang="sv" 
		className="html"
		suppressHydrationWarning>
			<head>
				<ColorSchemeScript
				      nonce="8IBTHwOdqNKAWeKl7plt8g=="

				defaultColorScheme="light"  />
				
			</head>
			<body suppressHydrationWarning>
				<Providers initialUser={userData}>
					{children}

				</Providers>
			</body>
		</html>
	)
}
